# Specific Confluent Cloud Configuration file.
# This profile with inherit all properties from application.yml
# But will override properties:
# spring.kafka.bootstrap-servers and schema.registry.url (part of spring.kafka.properties)

spring:
  kafka:
    bootstrap-servers: {bootstrap-url}
    consumer:
      auto-offset-reset: earliest
      group-id: kafkaSchemaGroup
    properties:
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 120000
      security.protocol: SASL_SSL
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{Username}" password="{password}" ;
      # Schema Registry specific settings
      schema.registry.url: {registry url}
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: KEY:SECRET